-- Create tables
-- Lookup
CREATE TABLE OrderType (
	ID INT IDENTITY(1,1),
	Type VARCHAR(30) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE OrderStatus (
	ID INT IDENTITY(1,1),
	Status VARCHAR(30) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE ProductType (
	ID INT IDENTITY(1,1),
	Type VARCHAR(30) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE UserType (
	Id INT IDENTITY(1,1),
	Type VARCHAR(30) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE Gender (
	ID INT IDENTITY(1,1),
	Name VARCHAR(30) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE FootSide (
	Id INT IDENTITY(1,1),
	Side VARCHAR(30) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE ShoeSize (
	Id INT IDENTITY(1,1),
	Size VARCHAR(10) NOT NULL,
    Code VARCHAR(10) NOT NULL,
	PRIMARY KEY(Id)
);

-- Main
CREATE TABLE UserProfile (
	Id UNIQUEIDENTIFIER,
	UserTypeId INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	Surname VARCHAR(50),
	Email VARCHAR(320) NOT NULL,
	GenderId INT,
	AddressId UNIQUEIDENTIFIER,
	PRIMARY KEY(Id),
	FOREIGN KEY(UserTypeId) REFERENCES UserType(Id),
    FOREIGN KEY(GenderId) REFERENCES Gender(Id),
);

CREATE TABLE Address (
	Id UNIQUEIDENTIFIER DEFAULT NEWID(),
	Country VARCHAR(50) NOT NULL,
	Province VARCHAR(50),
	City VARCHAR(50) NOT NULL,
	Suburb VARCHAR(50),
	PostalCode INT NOT NULL,
	StreetNumber VARCHAR(10) NOT NULL,
	StreetName VARCHAR(50) NOT NULL,
	UnitNumber VARCHAR(10),
	ComplexName VARCHAR(50),
	UserProfileId UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(UserId) REFERENCES UserProfile(Id)
);

CREATE TABLE [Order] (
	Id UNIQUEIDENTIFIER DEFAULT NEWID(),
	UserProfileId UNIQUEIDENTIFIER NOT NULL,
	OrderTypeId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(UserId) REFERENCES UserProfile(Id),
	FOREIGN KEY(OrderTypeId) REFERENCES OrderType(Id)
);

CREATE TABLE OrderStatusUpdate (
	Id UNIQUEIDENTIFIER DEFAULT NEWID(),
	OrderId UNIQUEIDENTIFIER NOT NULL,
	OrderStatusId INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(OrderId) REFERENCES [Order](Id),
	FOREIGN KEY(OrderStatusId) REFERENCES OrderStatus(Id)
);

CREATE TABLE Product (
	Id UNIQUEIDENTIFIER DEFAULT NEWID(),
	Brand VARCHAR(50) NOT NULL,
	Model VARCHAR(50) NOT NULL,
	Description VARCHAR(254),
	ProductTypeId INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(ProductTypeId) REFERENCES ProductType(Id),
	FOREIGN KEY(CreatedBy) REFERENCES UserProfile(Id)
);

CREATE TABLE ProductVariant (
	Id UNIQUEIDENTIFIER DEFAULT NEWID(),
	ShoeSizeId INT NOT NULL,
	FootSideId INT NOT NULL,
	Color VARCHAR(100) NOT NULL,
	Price FLOAT NOT NULL,
	Quantity INT NOT NULL,
	ProductId UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIME NOT NULL,
	CreatedBy UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(FootSideId) REFERENCES FootSide(Id),
	FOREIGN KEY(ShoeSizeId) REFERENCES ShoeSize(Id),
	FOREIGN KEY(ProductId) REFERENCES Product(Id),
);

CREATE TABLE OrderItems (
	OrderId UNIQUEIDENTIFIER,
	ProductVariantId UNIQUEIDENTIFIER,
	PRIMARY KEY (OrderId, ProductVariantId),
	FOREIGN KEY (OrderId) REFERENCES [Order](Id),
	FOREIGN KEY (ProductVariantId) REFERENCES ProductVariant(Id)
);
